development:
  adapter: postgresql
  enconding: unicode
  database: pds-dev
  pool: 5
  username: data
  password: data

test:
  adapter: postgresql
  encoding: unicode
  database: pds-test
  pool: 5
  username: data
  password: data
